android/app/src/androidTest/java/com/boostcampwm2023/snappoint/MediaRepositoryTest.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/MediaRepository.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/MediaRepositoryImpl.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/CreatePostUiState.kt
글을 작성할 때 생성하는 블록들의 배열을 UiState 내부에 선언했습니다.
repository를 통해 image에 uri에 대한 값을 요청하는 api를 선언했습니다.
@Provides와 @Binds의 차이를 제대로 이해하지 못해 고민을 많이 했습니다.
프로젝트에서 가지고 있는 클래스나 인터페이스이기 때문에 Binds 키워드를 통해 의존성 주입을 할 수 있도록 구현했습니다.
=> Feature(#33): 게시물 내용을 담는 `UiState` 생성 및 `repository` 생성

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt, android/app/src/main/res/drawable/icon_arrow_back.xml, android/app/src/main/res/drawable/icon_check.xml, android/app/src/main/res/drawable/icon_photo_block.xml, android/app/src/main/res/drawable/icon_text_block.xml, android/app/src/main/res/drawable/icon_video_block.xml, android/app/src/main/res/layout/fragment_create_post.xml, android/app/src/main/res/values/colors.xml, android/app/src/main/res/values/strings.xml, android/app/src/main/res/values/themes.xml, android/gradle/libs.versions.toml, android/gradle/wrapper/gradle-wrapper.properties
- `CreatePostFragment`를 `BaseFragment`를 상속받도록 구현하였습니다.
- 해당 `Fragment`의 XML 파일을 생성하고, UI 레이아웃을 작성하였습니다.
<image src=https://github.com/boostcampwm2023/and01-SnapPoint/assets/85796984/84619438-9cca-47b9-8e6a-5d97f30aa12a width=270 height=600>
=> Feature(#9): 게시물 작성 화면 UI 구현

android/app/build.gradle.kts, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/ImageResponse.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/ImageUriResponse.kt, android/app/src/test/java/com/boostcampwm2023/snappoint/MediaRepositoryTest.kt, android/gradle/libs.versions.toml
현재는 서버의 api 명세가 나오지 않아 임의로 작성한 상태입니다.
mockwebserver를 이용해 서버의 응답 값을 임의로 추가해 api 자체에 대한 unitTest만 작성한 상태입니다.
다른 요구사항을 구현할 때, repository에 대한 test를 진행할 예정이고, 이 때 작성한 mockserver를 이용할 예정입니다.
명세가 나오지 않은 상태에서 값들을 예상해 테스트코드를 작성하는 것이 자기만족에 그칠 것 같은 생각이 들었습니다.
실제로 사용되는 테스트코드들의 예시를 더 보고 보완해야 할 것 같습니다.
=> Feature(#33): 네트워크 요청 API 작성

backend/.prettierrc, backend/prisma/schema.prisma, backend/src/app.controller.spec.ts, backend/src/app.controller.ts, backend/src/app.module.ts, backend/src/app.service.ts, backend/src/prisma.service.ts
- Prisma Client 설정하고, 테스트를 위해 User 생성 및 조회 코드 작성
- NCP 클라우드 연동 위해 Shadow DB 수동 설정 및 연결
- Prisma Client 설정하고, 테스트를 위해 User 생성 및 조회 코드 작성
- NCP 클라우드 연동 위해 Shadow DB 수동 설정 및 연결
- Local DB로 테스트 할 떄는 잘 됬지만, NCP MySQL와 연동 시 `P3014` 에러가 발생했습닌다.
- 찾아보니 `Prisma`는 고가용성과 백업을 위해 따로 `Shadow DB` 를 만들다는 것을 알았고, 이 권한이 없어 발생한 문제였습니다.
- 그래서 `MySQL`에서 권한 부여하려고 했으나, 클라우드 완전 관리형 DB여서 DB 생성 권한을 줄 수 없었습니다.
- `NCP Reference`를 참고해, `Console`에서 DB를 설정할 수 있다는 것을 알았고 수동으로 config를 설정해 해결했습니다.
**References**
* https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database
* https://guide.ncloud-docs.com/docs/database-database-5-2
=> Setting(#77) Prisma Client 설정 및 NCP DB와 연결

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/PostBlockListAdapter.kt
- `itemView`가 화면에서 사라져도 Listener가 살아있어 데이터가 유실된다고 판단
- Listener를 제거하려면 `TextWatcher`의 인스턴스로 제거하는 방법밖에 없는 것 같아, `TextWatcher`를 상속받아 Listener를 실행하는 클래스를 구현하고, 이를 `ViewHolder`에 인스턴스로 생성하여 함께 관리
- Adapter에서 `onViewAttachedToWindow`가 호출될 때 `TextWatcher`도 함께 추가하고, `onViewDetachedFromWindow`가 호출될 때 제거하여 데이터가 유실되는 문제 해결
- 처음에는 `TextWatcher`를 전부 구현하지 않고 필요한 부분만 구현해서 추가해주려고 했는데, `TextWatcher`인스턴스가 없으면 제거를 해줄 수 없는 것 같아 결국 사용하지 않는 부분을 포함하는 `TextWatcher` 구현체를 구현하였다. 
- `ListAdapter`를 사용하면 대부분 해결될 문제인 것 같은데, data class 내에 동일한 객체임을 보여줄 수 있는 `id`같은 unique한 속성이 없어서 `ListAdapter`를 사용하지 못했다. `ListAdapter`를 사용하기 위해 data class에 unique한 속성을 추가해주는 것이 맞는지 모르겠다.
=> Feature(#37): `RecyclerView` itemView의 Attach 여부에 따라 TextWatcher 관리

android/app/src/androidTest/java/com/boostcampwm2023/snappoint/CreatePostViewModelTest.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostEvent.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt, android/app/src/main/res/layout/fragment_create_post.xml, android/app/src/main/res/values/strings.xml
게시글에 있는 block들에 대해 content의 값을 기준으로 유효성 검사를 진행하게 구현한 상태입니다.
유효하지 않은 부분에 대해서는 sharedFlow를 통해 이벤트를 UI에 전달할 수 있도록 구현했습니다.
현재는 메시지를 Toast의 형태로 전달했고, 메시지 표시 방법에 대한 논의가 필요할 것 같습니다.
=> Feature(#20): 게시물 작성 이벤트 전달 및 입력값 유효성 검사

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt, android/app/src/main/res/layout/fragment_create_post.xml, android/app/src/main/res/layout/item_image_block.xml, android/app/src/main/res/layout/item_text_block.xml
- 각 `PostBlock`의 휴지통 버튼을 클릭하면, 해당 `PostBlock`이 `UiState`의 `postBlocks`에서 제거된다.
- RecyclerView Adapter에서 관리하는 리스트에서도 해당 아이템이 제거되며, `notifyItemRemoved()`와 `notifyItemRangeChanged()`메소드를 통해 변경 사항이 반영되고 화면이 업데이트된다.
- 처음에는 아이템 추가나 변경과 함께 바인딩 어댑터에서 구현하려 했는데, 그러면 어느 인덱스의 아이템이 제거된 것인지 알려주기가 번거로웠다. 그래서 그냥 RecyclerView.Adapter에서 아이템 삭제 시 필요한 동작들을 구현하고, ViewHolder에 해당 동작들을 람다 함수로 넘겨서 휴지통 버튼이 클릭되면 해당 동작들이 실행되도록 구현하였다.
=> Feature(#29): 게시물 블록 삭제 기능

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt, android/app/src/main/res/layout/fragment_create_post.xml, android/app/src/main/res/layout/item_image_block.xml, android/app/src/main/res/layout/item_text_block.xml
- 게시물 블록의 수정 버튼을 클릭하면 해당 블록이 하이라이트되고, 버튼이 바뀌는 편집 모드가 된다.
- 편집 모드에서 위 또는 아래 버튼을 클릭하면 UiState의 데이터의 위치가 변경되고, RecyclerView에도 반영된다.
- 편집 모드에서 체크 버튼을 누르게 되면 다시 이전 상태로 복구된다.
- 순서를 변경할 때 EditText에 포커스가 있다면 해당 포커스는 움직이지 않고 그 자리에 고정되는 문제가 있었습니다.
- 일단 수정 버튼이나 위 아래 버튼을 클릭하면 포커스가 해제되도록 구현하였습니다.
=> Feature(#31): 게시물 블록 위치 변경 기능 구현

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostListAdapter.kt, android/app/src/main/res/layout/fragment_around.xml, android/app/src/main/res/layout/item_around_post.xml, android/app/src/main/res/values/strings.xml
- 게시글 목록 화면의 UI 레이아웃을 XML로 작성하였습니다.
- 주변 게시글 목록 화면인 `AroundFragment`의 `ViewModel`과 `UiState`를 작성하였습니다.
- 주변 게시글 목록을 보여주는 `RecyclerView`를 `ListAdapter`를 이용하여 구현하였습니다.
- `ListAdapter`의 아이템은 `UiState`의 `posts`를 사용하고, `BindingAdapter`로 `RecyclerView`를 초기화하도록 구현하였습니다.
<image src=https://github.com/boostcampwm2023/and01-SnapPoint/assets/85796984/7621ded7-01ec-479f-ab60-2451a3f1c45d width=270 height=600>
=> Feature(#30): 게시글 목록 확인

android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepository.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostEvent.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/markerpointselector/MarkerPointSelectorActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/MetadataUtil.kt, android/app/src/main/res/layout/item_text_block.xml
presentation layer에 있는 post 관련 state들을 model 패키지 내부에 정의했습니다.
around fragment의 UiState 요소를 교체했습니다.
MainActivity에서 게시글의 목록을 가지고 있도록 했습니다.
속해있는 fragment에서 해당 게시물들의 list 변화를 대응할 수 있도록 구현했습니다.
=> Feature(#104): 메인 화면에서 게시글 목록을 보유하도록 하기

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt, android/app/src/main/res/layout/activity_main.xml
marker에 표시하기 위한 데이터를 MainActivity의 Uistate로 정의했습니다.
사진 추가 시 데이터 구조가 변경될 예정입니다.
게시물들을 구분하는 고유값이 존재해야 할 것으로 예상이 됩니다.
api가 나오지 않은 시점에서, mock 데이터를 이용하는 중에서는 post의 index 값을 게시물의 고유한 값으로 생각하고 개발하려 합니다. 의견 있으시면 말씀해주세요 :)
=> Feature(#44):  게시물을 바탕으로 지도에 snappoint 표시

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivityEvent.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/mainbindingAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/fragment_preview.xml, android/app/src/main/res/menu/preview_app_bar_menu.xml
- **임시로 FAB에 미리보기 화면으로 전달하는 이벤트를 연결했습니다.**
- MainActivity의 `uiState`에 미리보기 화면의 `lifecycle`에 맞게 값을 변경하는 Boolean Type 변수를 추가했습니다.
- 미리보기 화면이 열리면 `검색`, `FAB`가 사라지고 `TopAppbar`가 나타납니다.
- 바텀 시트는 가운데에 고정됩니다.
- BindingAdapter로 `뒤로가기`, `닫기` 이벤트를 연결했습니다.
- 분명 `drawer_icon_click`을 보고 따라했는데 빌드 에러가 자꾸 나와서 이벤트를 연결할 때 변수로 연결했습니다. 왜 이럴까요??
```
// 전
navigation_icon_click="@{() -> vm.appbarBackIconClicked()}"
// 후
navigation_icon_click="@{vm.appbarBackIconClicked}"
```
참고: https://stackoverflow.com/questions/67404315/android-databinding-bindingadapter-error-missing-return-statement
- 열기
- 닫기
=> Feature(#6, #22): 미리보기 화면 상단 바

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundEvent.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/res/layout/fragment_around.xml
- 게시글 목록에서 미리보기 버튼 클릭 시 해당 게시글의 인덱스를 MainViewModel의 UiState에 전달하고, MainActivity에선 UiState의 selectedIndex 값이 -1보다 크다면 게시글이 선택된 것으로 간주하고 해당 게시글의 마커들을 모두 지도에 그리도록 구현하였습니다.
- 마커를 생성할 때 PolylineOptions()를 통해 마커 사이를 잇는 선을 함께 생성해서 지도에 표시해주도록 구현하였습니다.
<image src=https://github.com/boostcampwm2023/and01-SnapPoint/assets/85796984/350722a7-28a9-4cb1-afa9-d372e4931d5d width=270 height=600>
=> Feature(#43): 미리보기 화면 마커/경로

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivityEvent.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/fragment_around.xml
- 미리보기 버튼을 클릭하면 이벤트로 해당 게시글의 인덱스를 전달하고 미리보기 화면을 띄우도록 구현하였습니다.
- 미리보기 화면으로 이동할 때 바텀시트의 state를 `HALF_EXPANDED`로 변경하도록 구현하였습니다.
- Preview Fragment가 destroy될 때 MainActivity의 `selectedIndex`를 -1로 바꿔, 다시 전체 마커가 지도에 표시되도록 구현하였습니다.
=> Feature(#43): 미리보기 화면으로 이동

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/mainbindingAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt, android/app/src/main/res/navigation/nav_bnv.xml
- 하단 네비게이션 클릭 이벤트 구현
- 네비게이션 이동 시 이전화면은 `backstack`에서 제거
- 코드 줄 바꿈 개선
- lifecycle 콜백 내부에서 해결하려다 보니 잘 진행이 안 됐습니다.
- `navController.navigate()`함수로 종료되지 않은(onDestroy가 호출되지 않은) fragment를 불러오려 하면 아무런 행동을 하지 않습니다.
- `AroundFragment`는 다른 화면으로 넘어가면 `onStop`까지만 진행이 돼서, `onStop` 내부에서 `backstack`삭제를 시도했는데 런타임오류로 잘 되지 않았습니다.
- 그래서 `Bottom Navigation View`의 이벤트를 오버라이딩해서 직접 구현한 다음 메인 액티비티에서 Fragment간의 이동을 관리하도록 수정했습니다.
- 탭 변경하는 부분 스크린샷
=> Feature(#32): 미리보기 화면에서 하단 네비게이션 이벤트 수정

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemEventListener.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/res/layout/activity_create_post.xml, android/app/src/main/res/layout/item_image_block.xml
- Bottom Sheet가 접힌 상태에서 Bottom Navigation View의 아이템 클릭 시 Bottom Sheet가 바로 나오도록 구현하였습니다.
- 주변 게시글 화면과 게시글 작성 화면과 관련된 코드의 리팩토링을 진행하였습니다.
- Bottom Navigation View의 아이템을 클릭할 때 Bottom Sheet의 state가 `STATE_COLLAPSED`라면 `STATE_HALF_EXPANDED`로 설정하도록 구현하였습니다.
- 주변 게시글 화면과 게시글 작성 화면에 관련된 코드들의 리팩토링을 1차적으로 진행하였습니다. 그 중 RecyclerView의 아이템에 클릭 리스너를 전달할 때 `Adapter`와 `ViewHolder`에 파라미터가 너무 많아지는 문제를 `interface`를 통해 전달하도록 수정하여 해결하였습니다.
=> Refactor: 안드로이드 코드 리팩토링

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/PostItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt, android/app/src/main/res/layout/item_around_post.xml
- 지도상의 스냅포인트를 클릭 시 바텀 시트에 미리보기 화면이 표시
- 클릭한 스냅포인트의 사진을 보여주도록 구현
- 게시글 목록에서 제목 앞에 사진 추가
- 게시글 목록의 아이템 클릭 시 확장 버튼과 동일한 동작 수행
- 스냅포인트 터치 시 미리보기 화면을 띄워주도록 구현하였습니다.
- 미리보기 화면에서는 터치한 스냅포인트에 해당하는 사진을 보여주도록 구현하였습니다.
- 게시글 목록 화면의 아이템에 사진을 추가하였습니다.
- 게시글 목록의 각 아이템의 root view에 확장 버튼과 같은 동작을 수행하도록 `setOnClickListener`를 지정하였습니다.
[Screen_recording_20231123_221559.webm](https://github.com/boostcampwm2023/and01-SnapPoint/assets/85796984/625db3a0-06d4-4b1d-a7b4-87ba1ee91cf5)
[Screen_recording_20231123_225414.webm](https://github.com/boostcampwm2023/and01-SnapPoint/assets/85796984/a42b09a9-2da0-47d7-8e9c-c8dce85c3f7a)
=> Feature(#32): 스냅포인트 클릭 시 미리보기 및 게시글 목록 수정

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
- 각 스냅포인트에 해당 위치의 이미지를 표시합니다.
- 데이터를 구글본사 주변으로 이동했습니다 (가상기기 위치)
- 현재 위치 찾아가기 + 축소
경로가 보이는 건 아직 정건님 브랜치와 머지가 안 돼서 생긴 버그입니다.
=> Feature(#7): 스냅 포인트 이미지 설정

.github/workflows/android-firebase-app-distribution.yml
keystorepassord를 찾을 수 없는 오류 - working directory가 달라 발생한 오류로 예상. 수정
=> Refactor: cd actions job 나누기

android/app/build.gradle.kts, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivityEvent.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/search/AutoCompletionViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/search/SearchViewListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/search/SearchViewUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/Constants.kt, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/item_search_auto_complete.xml, android/app/src/main/res/values/strings.xml, android/gradle/libs.versions.toml
- ~SearchView에서 키워드 입력 시, 0.5초간 기다렸다가 더 이상 입력이 없으면 해당 키워드로 자동완성을 요청 (Places API)~
- SearchView에 `setOnEditorActionListener`메소드를 통해 검색 버튼 클릭 시 현재 입력된 키워드를 가져와 검색 결과가 존재하면 ~해당 위치로 지도 카메라 이동~ RecyclerView로 검색 결과 표시 (Places API)
- SearchView의 검색결과 각 아이템에 클릭리스너를 달아 해당 위치로 지도 카메라 이동하도록 구현
- `Geocoder`의 `getFromLocationName`메소드가 `deprecated`되어, 버전을 나눠 분기 처리
- 검색결과를 어떻게 구현할지 고민하다가, Google Maps에서 Places라는 API를 지원해서 해당 API를 통해 키워드에 대한 주소 검색 결과를 받아옴
- 주소를 받아오는 것은 현재 스레드를 block할 수 있음. 파라미터에 listener가 있는 `getFromLocationName`메소드는 해당 리스너 내에서 검색 결과를 받아와 작업을 하면 해당 문제가 해결되는데, API버전이 33이상이어야 해서 버전에 따른 분기 처리를 해주고, listener가 없는 `getFromLocationName`은 코루틴으로 실행되도록 구현함
=> Feature(#34): 주소 검색 및 카메라 이동

android/app/build.gradle.kts, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/res/layout/activity_main.xml
- 버튼 클릭 시 `GoogleMap.projection.visibleRegion.latLngBounds`를 통해 현재 지도 화면에 보이는 지역에 대한 정보 중 왼쪽 아래와 오른쪽 위의 좌표를 가져온다.
=> Feature(#40): 현재 위치에서 다시 검색

backend/src/api/post-api/post-api.controller.ts
post-api의 sign-in 임시 처리 제거
- 타 API와 충돌로 인해 임시로 로그인하는 처리를 제거
=> Fix: post-api의 sign-in 임시 처리 제거

backend/src/api/auth/auth.controller.ts, backend/src/api/auth/auth.module.ts, backend/src/api/auth/auth.service.spec.ts, backend/src/api/auth/auth.service.ts, backend/src/common/guards/jwt-auth.guard.ts, backend/src/common/strategies/auth.jwt.strategy.ts, backend/src/domain/refresh-token/refresh-token.service.ts
- 엑세스 토큰 만료시 자동 재발급 구현
- 
- 엑세스 토큰 만료시 자동 재발급 구현
- `authGuard`에서 재발급하도록 수정
- `authController`, `authService` 리프레시 로직 제거
- 리프레시 토큰 만료시 에러 처리
```json
{
"message": "리프레시 토큰이 만료되었습니다.",
"error": "Unauthorized",
"statusCode": 401
}
```
=> FIX: 엑세스 토큰 만료시 재발급

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MarkerUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/mainbindingAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SnapPointUtil.kt
- marker를 map에 추가할 때 해당 marker를 반환하는데, 이를 이용해 선택된 스냅포인트를 그릴 때 해당 marker를 보관해뒀다가 선택이 바뀔 때 보관했던 marker를 remove() 로 지도에서 제거하고, 새로 그린 마커를 다시 보관하도록 하여 모든 marker가 다시 그려지는 문제를 해결
=> FIX: MainUiState가 업데이트 될 때 불필요한 UI도 업데이트 되는 문제 수정

android/app/src/main/java/com/boostcampwm2023/snappoint/data/local/PostDatabase.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/local/converter/PostTypeConverter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/local/dao/PostDao.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/local/entity/SerializedPost.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepository.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/RoomRepository.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/RoomRepositoryImpl.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/di/RoomModule.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/subscription/SubscriptionFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/subscription/SubscriptionViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/PostCreation.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostEvent.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/post/PostViewModel.kt, android/app/src/main/res/layout/fragment_post.xml, android/app/src/main/res/layout/fragment_subscription.xml
- 게시글 작성 시 PostCreationState로 관리
- 게시글 열림 시 PostSummaryState로 관리
- bitmap 삭제 및 직렬화
- Room 구현
- Database, Entity, Dao, Repository
- 리스트나 클래스는 바로 저장하지 못 하기 때문에 `PostSummaryState`를 직렬화 해서 `Json`으로 저장했습니다.
- PostSummaryState를 바로 저장하면 DAO에서 presentation layer를 직접 참조하게 돼서 일단은 Entity를 남겨뒀습니다.
- 게시글이 수정된다면 저장된 게시글도 업데이트 해야할까요??
- 이전 게시글을 저장하고 나중에 수정된 게시글을 다시 저장한다면 어떻게 작동하는 것이 좋을까요?? 
- 둘 다 저장하기 or 덮어쓰기
- Post 화면
- Log
=> Feature(#216): 게시글 로컬에 저장

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/auth/signin/SignInFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/auth/signup/SignupFragment.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/auth/signup/SignupViewModel.kt, android/app/src/main/res/values/strings.xml
- 화면 전환 전에 현재 위치를 확인하는 방법으로 종료되는 현상을 해결했습니다.
```
if (currentDestination?.id != R.id.signUpFragment) {
navigate(R.id.action_loginFragment_to_signupFragment)
}
```
- 회원가입 성공시 실패 문자열을 표시하는 것을 수정했습니다.
- 별명을 3글자 이상 입력 받도록 했습니다.
- 회원가입 시도
[Screen_recording_20231205_231759.webm](https://github.com/boostcampwm2023/and01-SnapPoint/assets/76683420/64511150-579d-44bd-a2b1-8d1ba32a915b)
=> Fix: 네비게이션 화면 전환 수정

backend/src/api/file-api/file-api.controller.spec.ts, backend/src/api/file-api/file-api.service.spec.ts, backend/src/api/post-api/post-api.controller.spec.ts, backend/src/api/post-api/post-api.service.spec.ts, backend/src/api/post-api/post-api.service.ts, backend/src/api/validation/validation.service.spec.ts, backend/src/common/health/health.controller.spec.ts, backend/src/common/redis/redis-cache.service.spec.ts, backend/src/common/redis/redis-cache.service.ts
- Redis 캐싱 key, value 형태 수정
- mget, mset 구현
- 전체적인 형태는 string: string 저장
- 블럭의 경우 `block:{PostUuid}`; 
- 파일의 경우 `file:{BlockUuid}`;
- 이런식으로 수정
한 포스트 읽으면  
안에 블럭, 파일들 다 저장했습니다  
최대한.. 테스트 코드 고쳐볼라했는데...  
저희 시간 잡고 테스트 코드 짜는거도 해봐야될거 같습니다 
- set 컬렉션 보단 string으로 저장
- 배치로 가져오는것에서 
- 파일이 캐시에 없는 것들만 배치로 디비에서 가져오도록 구현했습니다
- mset, mget으로 안에서 비교해 콜백 실행하도록 구현
캐싱 없을 때 = 모두다 디비에서  
캐싱 있을 때
첫번째 요청에서 prisma 이슈로 좀 딜레이가 있습니다
=> Feature(): Redis 캐싱 key, value 형태 수정

android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/VideoAbortRequest.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/VideoEndRequest.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/VideoUrlRequest.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/VideoEndResponse.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/VideoStartResponse.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/VideoUrlResponse.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/auth/signin/SignInViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/PostCreation.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/splash/SplashActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/Constants.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/VideoEditActivity.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/VideoEditViewModel.kt, android/app/src/main/res/layout/activity_video_edit.xml, android/app/src/main/res/layout/item_video_block.xml
pre-signed api를 이용해 미디어 서버에 직접 업로드 할 수 있도록 구현했습니다.
안드로이드 버전 11부터는 개발자가 파일에 접근에 수정 및 조작이 불가능했습니다.
갤러리에서 가져온 요소의 절대 경로를 코드 상으로 얻을 수 없었기 때문에, 파일을 먼저 인코딩한 후 캐시 디렉토리에 저장하고, 해당 경로를 바탕으로 업로드 할 수 있도록 구현했습니다.
인코딩을 진행한 파일이 6MB에서 200KB로 줄었습니다.
화질과 용량의 관계를 파악하는 과정이 필요할 것 같습니다.
=> Feature(#15, #36): 영상 블록을 포함한 게시글 생성

.github/workflows/android-firebase-app-distribution.yml
gitgub actions로 설정한 android cd 브랜치의 트리거 기준을 main브랜치로 merge 했을 때로 변경했습니다.
=> [FIX] change `android cd` trigger branch (main)

android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/SnapPointClusterRenderer.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/clusterpreview/ClusterItemViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/search/SearchResultViewHolder.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/search/SearchViewListAdapter.kt, android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/viewpost/ViewPostViewModel.kt
- API가 닉네임과 이메일도 보내주도록 수정되었는데, 그에 따라 게시글에 작성자의 닉네임도 표시되도록 수정
- `ClusterItemViewHolder`에서 item의 타입에 따라 480p의 이미지 혹은 썸네일을 bind 하도록 수정
=> Feature: 기능 추가에 따른 개선

backend/src/api/api.module.ts, backend/src/api/post-api/post-api.controller.spec.ts, backend/src/api/post-api/post-api.service.spec.ts, backend/src/api/post-api/post-api.service.ts, backend/src/api/summarization/dtos/summary-post.dto.ts, backend/src/api/summarization/summarization.service.ts, backend/src/api/summarization/summarizationi.controller.ts, backend/src/main.ts
게시글 내용을 NCP의 API를 호출해 요약해 약 500ms의 응답 시간이 발생하였다. (Postman 기준) 이를 비동기 메시지 큐 방식으로 최적화하였다.
- NCP의 API를 사용한다는 점에서, 너무 잦은 API 호출, 지연된 작업으로 메시지 소실이 염려되었음
- 그러므로 [API 명세](https://api.ncloud-docs.com/docs/ai-naver-clovasummary-api)를 참고해, 회복 불가능한 오류인 경우 다시 수행하도록 구현
- 회복 가능한 오류는 `Promise`의 예외 처리에 따라, 다시 메시지를 `requeue` 하였음
=> Refactor: 게시글 요약 기능을 비동기 메시지 큐로 개선

backend/src/api/api.module.ts, backend/src/api/post-api/post-api.service.ts, backend/src/api/transformation/transformation.service.ts, backend/src/api/validation/dtos/validate-block.dto.ts, backend/src/api/validation/dtos/validate-post.dto.ts, backend/src/api/validation/validation.service.ts, backend/src/app.module.ts, backend/src/common/utility/utility.module.ts, backend/src/common/utility/utility.service.spec.ts, backend/src/common/utility/utility.service.ts, backend/src/domain/block/block.service.ts, backend/src/domain/block/dtos/find-blocks.dto.ts
PostApiService에서 `accessPost` 처럼 게시글 검증하는 메소드가 있고, 블록의 경우 수정하는 경우에 추가로 "다른 게시글 블록에 접근" 및 "타입을 변경"하는지 검증하였음
=> Feature: 게시글 생성, 수정 시 검증 로직 추가
