boostcampwm2023/and01-SnapPoint

.gitignore
backend/package.json
backend/prisma/schema.prisma
backend/yarn.lock

Prisma 패키지 구축 및 스키마 작성
* BE 프로젝트에 Prisma 패키지 설치 및 기본 설정
* ERD 설계 참고해 Model과 필드 추가
* 제약 조건을 모두 Code에서 관리하기로 결정해서, 스키마 오류 감지에 탁월한 Prsima를 선택했다.

Feature(#77): Prisma 구축 및 `스키마` 작성

---

android/app/build.gradle.kts
android/app/src/androidTest/java/com/boostcampwm2023/snappoint/MediaRepositoryTest.kt
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/MetadataUtil.kt
android/gradle/libs.versions.toml

- 이미지의 경로를 입력 받아서 위치 정보를 Result 타입으로 반환하는 함수 생성
- 위치 데이터의 유무를 확인하는 테스트 코드 작성
- 파일의 위치 데이터
- 추출한 위치 데이터
- 테스트 결과

Feature(#13): 이미지에서 메타데이터 가져오기

---

android/app/build.gradle.kts
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
android/app/src/main/res/layout/activity_maps_marker.xml
android/build.gradle.kts
android/gradle/libs.versions.toml

- **SDK 설치와 API_KEY 추가는 꼭 해주세요**
- Maps SDK 설치
- API Key 추가
- 지도 추가
```
val map: SupportMapFragment = supportFragmentManager.findFragmentById(R.id.map) as SupportMapFragment
map.getMapAsync(this)
```

Feature(#42): 화면에 지도 표시하기

---

.github/workflows/backend-cd.yml
backend/.dockerignore
backend/Dockerfile
backend/package.json

- Backend NCP server로 deploy 구현
- Backend NCP server로 deploy 구현
- `Dockerfile` 작성
- `backend-cd.yml` 작성
- NCP docker image registory 설정
- server instance docker 및 의존성 설치
- github actions
- PR 상태 조건 분기
```yml
on:
pull_request:
branches:
- main
types: // types closed 추가
- closed
```

Setting(#74):  Backend CD 구축

---

android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepository.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
android/app/src/main/res/values/strings.xml
android/app/src/test/java/com/boostcampwm2023/snappoint/PostRepositoryTest.kt

연결된 클릭 이벤트와 유효성 검증을 토대로  ViewModel 에서 SnapPoint repository를 통해 flow로 api 요청을 수행할 수 있게 구현했습니다.
요청에 대한 body 값은 기획 회의를 통해 기본적인 틀을 만든 상태이며, 추후 생성해 매핑할 수 있도록 구현할 예정입니다.

Feature(#20): CreatePostViewModel repository 연결 및 api 호출

---

android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostEvent.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/featurelist/FeatureListFragment.kt
android/app/src/main/res/layout/fragment_create_post.xml
android/app/src/main/res/layout/fragment_feature_list.xml
android/app/src/main/res/navigation/nav_graph.xml

api요청이 시작되고, 종료되기 전까지 ProgressBar를 표시할 수 있도록 구현했습니다.
기능 구현을 확인하기 위해 FeatureListFragment를 만들었고, 버튼을 통해 구현한 기능들을 우선적으로 확인할 수 있도록 화면 로직을 수정하였습니다.

Feature(#21): 서버 api 요청 화면 로직

---

android/app/src/androidTest/java/com/boostcampwm2023/snappoint/CreatePostViewModelTest.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostEvent.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostUiState.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/map/MapsMarkerActivity.kt
android/app/src/main/res/layout/activity_maps_marker.xml
android/app/src/main/res/layout/fragment_create_post.xml

Feature(#95): 좌표를 주소로 변환해 가져오기

---

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt

- EditText에 입력 할 때 마다 계속 EditText의 값을 업데이트해줘서 포커스를 잃는 문제를 notify 메소드를 세분화하여 수정

FIX: EditText 입력 시 포커스 잃는 문제 수정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/MainActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/around/AroundFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/markerpointselector/MarkerPointSelectorActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/popularpost/PopularPostFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/subscription/SubscriptionFragment.kt
android/app/src/main/res/layout/activity_main.xml
android/app/src/main/res/layout/activity_maps_marker.xml
android/app/src/main/res/layout/fragment_around.xml
android/app/src/main/res/layout/fragment_popular_post.xml
android/app/src/main/res/layout/fragment_setting.xml
android/app/src/main/res/layout/fragment_subscription.xml
android/app/src/main/res/menu/bottom_navigation_menu.xml
android/app/src/main/res/navigation/nav_bnv.xml
android/app/src/main/res/values/strings.xml

- 바텀 시트 생성
- 바텀 네비게이션 뷰, 네비게이션 그래프 생성
- 각 menu에 대응하는 Fragment 4개 생성

Feature(#24): 바텀 시트, 바텀 네비게이션

---

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SnapPointUtil.kt

현재는 이미지를 불러와 CircleCrop한 형태로 보여집니다.
SnapPoint 표현에 필요한 이미지를 디자이너와 상의 후 결정해야 할 것 같습니다.
추후, bitmap으로 불러온 이미지를 합쳐 SnapPoint로 표현할 예정입니다.

Feature(#7) Snap Point 표시

---

backend/src/file/dto/file.dto.ts
backend/src/post-api/post-api.service.ts

미디어 타입 검증 오류 수정, 파일 전송 시 MimeType 추가

Fix(#59, #63): 미디어 타입 검증 오류 수정, 파일 전송 시 MimeType 추가

---

backend/src/block/block.service.spec.ts

[TEST] 블록 도메인 서비스 테스트 코드 추가

---

backend/src/block/block.service.spec.ts

- 위도, 경도 중 하나라도 없으면 제대로 throw 발생하는지 추가

Test: 미디어 블록 좌표 검사 테스트 추가

---

backend/src/block/block.service.spec.ts

Block 도메인 서비스 테스트 코드 리팩토링
- 중복된 postUuid를 공통 변수로 분리

Refactor: 도메인 테스트 코드 리팩토링

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/PostBlock.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/CreatePostRequest.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/CreatePostResponse.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepository.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/BlockItemViewHolder.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostListAdapter.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/markerpointselector/MarkerPointSelectorActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewAdapter.kt
android/app/src/main/res/layout/activity_create_post.xml
android/app/src/main/res/layout/item_text_block.xml
android/app/src/main/res/navigation/nav_graph.xml

서버에서 나온 api를 적용했습니다. 
repository에 mapper가 존재해, data와 presentation layer 간 데이터를 매핑할 수 있도록 구현했습니다.

Feature(#20): 서버 api 연결

---

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt

- 스크롤 이벤트 중에 인덱스가 변경되면 uiState 업데이트
- 마커 클릭으로 uiState가 변경되면 이미지 위치 이동

Feature(#35): 보고있는 이미지와 스냅포인트의 하이라이트 연결

---

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/Constants.kt

- 지도 내부 bound를 설정해서 자동으로 `Zoom level` 조절
- 경로가 Bottom Sheet에 가려지지 않도록 약간 위로 올라가도록 조절
- bound 계산 과정
1. 보이는 구간은 실제 지도에 비해 작기 때문에 경로의 bound 위 아래로 bound를 추가해야 합니다.
2. 각 구간의 길이는 `binding.view.height`으로 알아낼 수 있습니다.
3. 비례식으로 위 아래로 추가해야 하는 bound를 계산합니다.
```
val newTopOfBound = topOfBound + heightOfBound * topAppBarRatio / visibleRatio
val newBottomOfBound = bottomOfBound - heightOfBound * (bottomNavViewRatio + bottomSheetRatio) / visibleRatio
```
- 세 기기 - Pixel 3a(1080x2220), SmallPhone Api 34(720x1080), Pixel Tablet(2566x1600, 가로모드) 확인 했습니다.
- 경로를 제외한 다른 스냅포인트는 지워야 잘 보일 것 같습니다.
- Pixel 3a(1080x2220)
- Pixel Tablet(2566x1600, 가로모드)
- SmallPhone Api 34(720x1080)

Feature(#128): 경로가 한 번에 보이도록 카메라 조절

---

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/preview/PreviewFragment.kt
android/app/src/main/res/layout/fragment_preview.xml
android/app/src/main/res/layout/item_image_preview.xml

- 이미지가 작은 기기에서 짤리지 않도록 이미지의 크기를 `bottom sheet`, `guide line`으로 계산합니다.
```
rcvPreview.layoutParams.height = mainViewModel.bottomSheetHeight - glTop.top
```
- 흰 텍스트와 검은 그림자로 배경의 밝기와 상관없이 글씨가 잘 보이도록 개선
- `onCreate`, `onViewCreated`에서 View의 크기가 0으로 나오는 것을 `root.post`로 해결했습니다.
```
with(binding) {
root.post {
rcvPreview.layoutParams.height = mainViewModel.bottomSheetHeight - glTop.top
}
}
```
- 작은 해상도
- 큰 해상도

Feature(#45): 이미지 위의 텍스트가 잘 보이도록 개선

---

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/subscription/SubscriptionFragment.kt
android/app/src/main/res/layout/fragment_subscription.xml
android/app/src/main/res/values/strings.xml

금요일 시연용으로 구독 화면 내부에 게시물 생성 화면이동 버튼을 만들어 연결했습니다.

Feature: 구독 화면 내부에 게시물 생성 화면이동 버튼 연결

---

backend/src/api/auth/auth.controller.ts
backend/src/api/auth/auth.service.spec.ts
backend/src/api/auth/auth.service.ts
backend/src/api/auth/dto/refresh-auth.dto.ts
backend/src/api/post-api/post-api.controller.ts
backend/src/common/decorator/cookie.decorator.ts
backend/src/common/guards/jwt-auth.guard.ts
backend/src/domain/refresh-token/dto/delete-refresh-token.dto.ts
backend/src/domain/refresh-token/refresh-token.service.ts

Feature(#150, #152): 리프레시 토큰, 재발급, 삭제 api 구현

---

backend/src/api/auth/auth.controller.ts
backend/src/api/auth/auth.service.spec.ts
backend/src/api/auth/auth.service.ts
backend/src/api/auth/dto/refresh-auth.dto.ts
backend/src/api/post-api/post-api.controller.ts
backend/src/common/decorator/cookie.decorator.ts
backend/src/common/guards/jwt-auth.guard.ts
backend/src/domain/refresh-token/dto/delete-refresh-token.dto.ts
backend/src/domain/refresh-token/refresh-token.service.ts

Reverts boostcampwm2023/and01-SnapPoint#154

Revert "Release: test PR"

---

android/app/build.gradle.kts
android/app/google-services.json
android/build.gradle.kts
android/gradle/libs.versions.toml

CI/CD 및 테스트 앱 배포를 위해 Firebase 연결을 했습니다.

Release(v0.1.0): firebase 연결

---

backend/src/api/auth/auth.controller.ts

[DOCS]: 로그아웃 Swagger 설명 수정

---

android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/request/LoginRequest.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepository.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/LoginRepositoryImpl.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/di/RemoteModule.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/di/RepositoryModule.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/base/BaseFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/createpost/CreatePostActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginEvent.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginFormState.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
android/app/src/main/res/values/strings.xml

- `signin`으로 로그인 요청 보내기
- `SnapPointApi` 주소 변경 (`http://175.45.195.153:3000/`)
- 실패하면 Toast로 메시지 표시
- Response가 정해지지 않은 것 같아 `String`으로 받았습니다.
- 실패 메시지

Feature(#134, #136): 로그인 요청, 실패 메시지

---

.github/workflows/backend-dev-cd.yml
backend/src/api/auth/auth.controller.ts
backend/src/api/auth/auth.service.ts
backend/src/api/auth/dto/signup.dto.ts

- 회원가입 함수에서 기존 도메인 서비스를 사용하여 생성을 `authService`로 분리
- 회원가입 함수에서 기존 도메인 서비스를 사용하여 생성을 `authService`로 분리
- 중복된 이메일이 있는경우 409 에러 리턴
-

Fix(): 중복 회원가입 예외 처리

---

.github/workflows/android-firebase-app-distribution.yml

setting: android - develop branch merge 자동 배포

---

.github/workflows/android-firebase-app-distribution.yml
android/app/.gitignore

Feature: cd action create properties file

---

.github/workflows/android-firebase-app-distribution.yml

Refactor: android cd 필요없는 job 삭제

---

.github/workflows/android-firebase-app-distribution.yml

Setting: action checkout version 변경

---

.github/workflows/android-firebase-app-distribution.yml
android/app/build.gradle.kts
android/app/release/output-metadata.json

signingConfig를 설정하여 actions 실행 시 sign이 된 release apk를 생성할 수 있도록 했습니다.

Setting: signingConfig 설정 및 action 연결

---

.github/workflows/android-firebase-app-distribution.yml

Fix: actions 오타 수정

---

backend/src/api/post-api/post-api.controller.ts

- target branch 설정 미스로 인해 PR을 Revert

Revert: "Fix: post-api의 sign-in 임시 처리 제거"

---

backend/src/api/post-api/post-api.controller.ts
backend/src/api/post-api/post-api.service.ts

Post-API 상대 경로를 절대 경로로 수정
Post API 컨트롤러 및 서비스 상대 경로를 절대 경로 Import로 수정

Style: Post-API 상대 경로를 절대 경로로 수정

---

backend/src/api/auth/auth.controller.ts
backend/src/api/auth/dto/create-auth.dto.ts
backend/src/app.module.ts

- dto에 설정한 class-validator가 적용되지 않았음
- app.module에 전역으로 pipe 설정
- app.module에 전역으로 pipe 설정

Fix: 회원가입, 로그인시 dto validation 설정

---

.github/workflows/android-ci.yml

android 폴더가 변경되는 pr이 들어왔을 떄, ktlint를 실행해 결과를 pr review로 남깁니다.

Feature: andorid ci ktlint 적용

---

android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivity.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainActivityEvent.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MainViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingEvent.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingFragment.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/setting/SettingViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/signin/SignInViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/splash/SplashViewModel.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/util/SignInUtil.kt
android/app/src/main/res/layout/fragment_setting.xml
android/app/src/main/res/values/strings.xml

- 로그아웃 하면 로그인 화면으로 돌아갑니다.
- 로그아웃 하면 `SharedPreference`의 빈 문자열로 수정합니다.
- 로그아웃 후 애플리케이션 다시 실행
- 네트워크가 없는 환경에서 로그아웃 시도

Feature(#176): 로그아웃 추가 구현

---

backend/src/api/auth/auth.controller.ts

* 로그인하지 않아도 로그아웃 요청이 됬던 문제를 수정

Release: 로그아웃 API `NoAuth 제거` 릴리즈

---

backend/prisma/schema.prisma
backend/src/api/file-api/dto/file.dto.ts
backend/src/api/post-api/dtos/write-block-files.dto.ts
backend/src/api/transformation/transformation.service.ts
backend/src/common/mocks/mock.entites.file.ts
backend/src/domain/file/dtos/update-file.dto.ts
backend/src/domain/file/file.service.ts

- 썸네일 게시물 생성 시점에 추가할 수 있도록 수정
- 썸네일 게시물 생성 시점에 추가할 수 있도록 수정
- 파일 객체 안 선택적으로 `thumbnailUuid`에 넣을 수 있도록 수정했습니다.

Feature(): 썸네일 업로드, 게시물 생성 시점 썸네일 uuid 받도록 수정

---

android/app/src/main/java/com/boostcampwm2023/snappoint/data/mapper/PostMapper.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/SnapPointApi.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/PostBlock.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/CreatePostResponse.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/remote/model/response/GetPostResponse.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/data/repository/PostRepositoryImpl.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/main/MapManager.kt
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/model/Post.kt

변경된 서버의 api를 적용했습니다.
스냅포인트로 제공되는 이미지 및 동영상 블록들에 대한 url을 144p로 변경하였습니다.

Feat: 게시물 미디어 블록 api 변경사항 적용 및 스냅포인트 썸네일 이미지 적용

---

backend/src/api/post-api/dtos/write-block-files.dto.ts
backend/src/common/redis/redis-cache.service.ts

- 썸네일 업로드
- 레디스 mget
- 썸네일 uuid 옵셔널하게 받도록 수정
- mget에서 key가 안들어온 경우 예외 처리 해줬습니다

FIX(): 썸네일 업로드, 레디스 mget 수정

---

backend/src/api/validation/validation.service.ts

- 게시물 생성시 `0,0`으로 생성하면 에러를 뱉는 버그 수정
- 게시물 검증시 위도 경도를 `!`를 사용하여 검증했었음
- 0,0으로 오게 되면 에러 처리가 되어 정상적인 검증이 되지 않음
- `!` 대신 `!== undefined`로 주성

Fix: 위도 경도 검사시 ! 대신 undefined인지 검사하는 로직으로 변경

---

backend/src/api/post-api/post-api.service.ts

…작업 추가
- redis에서 가져오고 넣을때 이중 배열 형태로 가공
- redis에서 가져오고 넣을때 이중 배열 형태로 넣어줘야함
- 디비에서 가져올때는 일반 배열 형태로 가져오게 됨
- 실제 디비에서 가져오는 경우 이중 배열 형태로 가공하는 과정 추가

Fix: redis 버그 수정 / 실제 디비에서 가져오는 경우

---

android/app/build.gradle.kts
android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/videoedit/ThumbnailView.kt

[RELEASE] 0.2.0

---

backend/src/api/post-api/post-api.controller.spec.ts
backend/src/api/post-api/post-api.service.spec.ts
backend/src/api/post-api/post-api.service.ts
backend/src/domain/post/dtos/post.dto.ts
backend/src/domain/user/user.service.ts

- 게시물 정보 반환시 유저 정보도 같이 반환
- postDto 필드 추가
- email : 유저 이메일
- nickname : 유저 닉네임
- userService
- findUsers 선언
- findUsers
- isDeleted 고정 값??
- 고정으로 삭제되지 않은 경우만 체크하는것은 여기선 불필요하다고 판단함

Feature: 게시물 정보 반환시 유저 정보도 같이 반환

---

backend/src/api/post-api/post-api.controller.ts
backend/src/api/post-api/post-api.service.ts
backend/src/domain/block/block.service.ts
backend/src/domain/file/file.service.ts

게시글을 삭제하는 도메인 메소드, 이를 조합하는 애플리케이션 로직 구현

Feature: 게시글 삭제 기능 구현
